[package]
name = "dd_gui"
version = "0.1.0"
authors = ["Rob Saunders <rob@wearebrandnew.com>"]

[dependencies]
vst2 = { git = "https://github.com/overdrivenpotato/rust-vst2" }
log = "0.3"
simplelog = "0.4.2"
libc = "*"
conrod = { version = "0.52.0", features = ["piston", "glium", "winit"] }
winit = "0.5.9"

[lib]
name = "dd_gui"
crate-type = ["cdylib"]

# [replace]
# "winit:0.5.9" = { path = "deps/winit-0.5.11" }
